### ISSUE TITLE
I try to make this the default

### ISSUE THREAD

**Issue by deisi** [kabili207/docker-ot-recorder#1]
Hey, I'm currently working on a PR for onwtracks that makes an alpine based image the default for the owntracks project. To do so I reused parts of your Dockerfile at my repo [here](https://github.com/deisi/docker-ot-recorder). Therefore I want to know, If you want to be part of the authors list of this Dockerfile.

**Comment by kabili207** [comment]
Sure. I have changed my name since then (see my profile).

**Comment by deisi** [comment]
Okay, I pushed it into my repo. It will later show up in https://github.com/owntracks/recorderd witch will be renamed to docker-recorder.
